Product-page
hieunguyen64/RichFieldChairs-Project pull request #10
Opened 2020-04-17 04:23 UTC by hieunguyen64

Added a single product page. At homepage, when clicking on any product image, it will redirect to the single product page.
Removed class search-container2.
The logo will now be responsive.
Logo, search bar and cart button will now be on a row.
Optimized code.

2020-04-17 06:29 UTC, thienhophu requested changes

2020-04-17 06:29 UTC, thienhophu commented on Product-page/Product-page.html
> +                        </a>
remove this

2020-04-17 06:29 UTC, thienhophu commented on Product-page/css/Product-page.css
> +#favorites-btn{
extra line

2020-04-17 06:29 UTC, thienhophu commented on index.html
> +                        </a>
remove this

2020-04-17 07:33 UTC, hieunguyen64 commented on Product-page/Product-page.html
> +                        </a>
done

2020-04-17 07:34 UTC, hieunguyen64 commented on Product-page/css/Product-page.css
> +#favorites-btn{
done

2020-04-17 07:34 UTC, hieunguyen64 commented on index.html
> +                        </a>
done

2020-04-18 06:55 UTC, thienhophu approved these changes

2020-04-18 11:38 UTC, merged